cabal-version:      3.0
name:               solution
version:            0.1.0.0
synopsis:           Fibonacci demo (Haskell)
build-type:         Simple

executable solution
    main-is:          Solution.hs
    build-depends:    base >=4.18 && <5
    default-language: Haskell2010
    ghc-options:      -O2 -Wall
